TrajectoryPlannerROS:

  holonomic_robot: false
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.2
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4
  escape_vel: -0.1

  sim_time: 2.0
  meter_scoring: true
  pdist_scale: 0.6

TebLocalPlannerROS:
  xy_goal_tolerance: 0.1  # Distance tolerance for reaching the goal pose
  yaw_goal_tolerance: 0.15  # Orientation tolerance for reaching the desired go$

